product.name=WSO2 Carbon
product.version=4.10.81
product.key=Carbon
carbon.product.version=4.10.81
carbon.version=4.10.81
default.server.role=CarbonServer
hotdeployment=true
hotupdate=true
childfirstCL=true
jaxwsparam=true
