product.name=WSO2 Carbon
product.version=4.10.100
product.key=Carbon
carbon.product.version=4.10.100
carbon.version=4.10.100
default.server.role=CarbonServer
hotdeployment=true
hotupdate=true
childfirstCL=true
jaxwsparam=true
